# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=25)),
                ('num_critic_for_reviews', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('actor_2_name', models.CharField(max_length=30)),
                ('gross', models.IntegerField()),
                ('genres', models.CharField(max_length=50)),
                ('actor_1_name', models.CharField(max_length=50)),
                ('movie_title', models.CharField(max_length=50)),
                ('num_voted_users', models.IntegerField()),
                ('actor_3_name', models.CharField(max_length=30)),
                ('plot_keywords', models.CharField(max_length=100)),
                ('movie_imdb_link', models.CharField(max_length=100)),
                ('num_user_for_reviews', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('budget', models.IntegerField()),
                ('year', models.IntegerField()),
                ('imdb', models.IntegerField()),
            ],
        ),
    ]
