# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20171112_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='num_critic_for_reviews',
            field=models.IntegerField(null=True),
        ),
    ]
